matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      services:
        - xvfb
      before_install:
        - sudo apt-get install -y xclip;
    - os: osx
      sudo: required
language: csharp
mono: none
dotnet: 2.1.400
script:
 - dotnet build src --configuration Release
 - dotnet test src/Tests/Tests.csproj --configuration Release --no-build --no-restore