matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
      sudo: required
services:
  - xvfb
language: csharp
before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then sudo apt-get install -y xclip; fi
mono: none
dotnet: 2.1.400
script:
 - dotnet restore
 - dotnet build
 - dotnet test Tests/Tests.csproj --no-build