matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      services:
        - xvfb
    - os: osx
      sudo: required
language: csharp
before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then sudo apt-get install -y xclip; fi
mono: none
dotnet: 2.1.400
script:
 - dotnet build src --configuration Release
 - dotnet test src/Tests/Tests.csproj --configuration Release --no-build --no-restore